# Generated by Django 5.2.11 on 2026-02-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(default='EMP001', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
